linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 17
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable-all: false
  enable:
    - govet
    - gocyclo
    - dupl
    - goconst
    - misspell
    - lll
    - goimports
    - gocritic
  disable:
    - exhaustivestruct
    - wrapcheck
    - noctx
    - cyclop
    - tagliatelle
    - exhaustruct
    - ireturn

run:
  skip-files:
  skip-dirs:

issues:
  exclude-rules:
    - text: "Potential HTTP request made with variable url"
      linters:
        - gosec
    - text: "G108: Profiling endpoint is automatically exposed on /debug/pprof"
      linters:
        - gosec
