// Copyright 2020 wongoo. All rights reserved.

// Code generated by "makeStatic"; DO NOT EDIT.

package logtail

var indexHTMLContent = []byte(`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        pre {
            margin: 0;
            width: 100%;
            white-space: pre-wrap;
            white-space: -moz-pre-wrap;
            word-wrap: break-word;
        }
    </style>
    <script>
        const maxLines = 10000;
        let lineCount = 0;
        let ws;
        let output;

        function print(message) {
            let d = document.createElement("pre");
            d.innerText = message;
            output.appendChild(d);

            lineCount++
            if (lineCount > maxLines) {
                output.children.item(0).remove()
                lineCount--;
            }
            window.scrollTo(0, document.body.scrollHeight);
        };

        function restartTail() {
            ws = null;
            if (window.confirm("connection closed, reconnect?")) {
                startTail();
            }
        }

        function startTail() {
            if (ws) {
                return false;
            }
            ws = new WebSocket("ws://" + document.location.host + "/tail");
            ws.onopen = function (evt) {
            }
            ws.onclose = function (evt) {
                restartTail();
            }
            ws.onmessage = function (evt) {
                print(evt.data);
            }
            ws.onerror = function (evt) {
                print("ERROR: " + evt.data);
                try {
                    ws.close()
                } catch (e) {
                }
                restartTail();
            }
        }

        window.addEventListener("load", function (evt) {
            output = document.getElementById("output");
            startTail()
        });
    </script>
</head>
<body>
<div id="output"></div>
</body>
</html>`)
