// Copyright 2020 wongoo. All rights reserved.

// Code generated by "makeStatic"; DO NOT EDIT.

package logtail

var indexHTMLContent = []byte(`<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-size: 10px;
        }

        pre {
            margin: 0;
            width: 100%;
            white-space: pre-wrap;
            white-space: -moz-pre-wrap;
            word-wrap: break-word;
        }
    </style>
    <script>
        let maxLines = 10000;
        let lineCount = 0;
        let ws;
        let output;
        let scrollingFlag = true;
        let autoReconnectFlag = true;

        function scrollingControl(btn) {
            scrollingFlag = !scrollingFlag;
            btn.innerText = (scrollingFlag ? "stop" : "start") + " scrolling";
        }

        function autoReconnectControl(btn) {
            autoReconnectFlag = !autoReconnectFlag;
            btn.innerText = (autoReconnectFlag ? "disable" : "enable") + " auto connect";
        }

        function error(message) {
            let d = document.getElementById("error_msg");
            d.innerText = message;
        }

        function print(message) {
            let d = document.createElement("pre");
            d.innerText = message;
            output.appendChild(d);

            lineCount++
            while (lineCount > maxLines) {
                output.children.item(0).remove()
                lineCount--;
            }
            if (scrollingFlag) {
                window.scrollTo(0, document.body.scrollHeight);
            }
        }

        function restartTail() {
            ws = null;
            error("connection closed!");

            if (autoReconnectFlag) {
                error("connection closed, reconnect in 5s!");
                window.setTimeout(startTail, 5 * 1000);
            }
        }

        function startTail() {
            if (ws) {
                return false;
            }
            ws = new WebSocket("ws://" + document.location.host + "/tail");
            ws.onopen = function (evt) {
            }
            ws.onclose = function (evt) {
                restartTail();
            }
            ws.onmessage = function (evt) {
                print(evt.data);
            }
            ws.onerror = function (evt) {
                error("ERROR: " + evt.data);
                try {
                    ws.close()
                } catch (e) {
                }
                restartTail();
            }
        }

        function heartbeat() {
            if (ws != null) {
                ws.send("ok")
            }
            window.setTimeout(heartbeat, 5000)
        }

        window.addEventListener("load", function (evt) {
            output = document.getElementById("output");
            startTail();
            window.setTimeout(heartbeat, 5000)
        });
    </script>
</head>
<body>
<div style="width: 99%; position: fixed; text-align: right;">
    <label id="error_msg" style="color: red;"></label>
    max lines:<input type="text" value="10000" onchange="maxLines=parseInt(this.value)">
    <button onclick="scrollingControl(this);">stop scrolling</button>
    <button onclick="autoReconnectControl(this);">disable auto connect</button>
</div>
<div id="output"></div>
</body>
</html>`)
